volumes:
  photoview_data:
    name: 'mediacenter_photoview_data'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - '${JELLYFIN_ROOT}/config:/config'
      - '${JELLYFIN_ROOT}/cache:/cache'
      - '${JELLYFIN_ROOT}/media:/data/media'
  
    # ports:
      # - "8096:8096" # HTTP Port
      # - "8920:8920" # HTTPS Port

    ## Base Homelab config
    hostname: ${JELLYFIN_HOSTNAME}
    container_name: ${JELLYFIN_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped
  
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      - TZ=Europe/Paris
  
    # ports:
      # - 5055:5055
  
    volumes:
      - '${JELLYSEER_ROOT}/config:/app/config'

    ## Base Homelab config
    hostname: ${JELLYSEER_HOSTNAME}
    container_name: ${JELLYSEER_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped
  
  jdownloader:
    image: jlesage/jdownloader-2
    volumes:
      - "${JDOWNLOADER_ROOT}/media:/output:rw"
      - "${JDOWNLOADER_ROOT}/config:/config:rw"
  
    # ports:
      # - "5800:5800"

    ## Base Homelab config
    hostname: ${JDOWNLOADER_HOSTNAME}
    container_name: ${JDOWNLOADER_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    volumes:
        - ${KAVITA_ROOT}/media/manga:/manga
        - ${KAVITA_ROOT}/media/book:/book
        - ${KAVITA_ROOT}/data:/kavita/config
    ports:
      - "5000:5000"
  
    ## Base Homelab config
    hostname: ${KAVITA_HOSTNAME}
    container_name: ${KAVITA_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped

  photowiew:
    image: viktorstrate/photoview:2
    
    # ports:
    #  - "8000:80"
    
    environment:
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_DATABASE_DRIVER=sqlite
      - PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db
      - MAPBOX_TOKEN=${PHOTOVIEW_MAPBOX_TOKEN}

    volumes:
      - photoview_data:/app/cache
      - '${PHOTOVIEW_ROOT}/database:/app/database'
      - '${PHOTOVIEW_ROOT}/media/photos:/photos:ro'

    ## Base Homelab config
    hostname: ${PHOTOVIEW_HOSTNAME}
    container_name: ${PHOTOVIEW_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped