services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    # ports:
      # - "8282:80/tcp"
    environment:
      TZ: "Europe/Paris"
    # Volumes store your data between container upgrades
    volumes:
      - "${WALLOS_ROOT}/db:/var/www/html/db"
      - "${WALLOS_ROOT}/logos:/var/www/html/images/uploads/logos"
    
    ## Base Homelab config
    hostname: ${WALLOS_HOSTNAME}
    container_name: ${WALLOS_NAME}
    network_mode: ${STACK_NETWORK}
    restart: unless-stopped